apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: "agones-s21992"
spec:
  container: agones-s21992-container
  ports:
    - name: default
      portPolicy: Static
      container: simple-game-server
      containerPort: 7654
      hostPort: 7777
      protocol: UDP
  health:
    disabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3
  sdkServer:
    logLevel: Info
    grpcPort: 9357
    httpPort: 9358
  template:
    spec:
      containers:
        - name: agones-s21992
          image:  gcr.io/agones-s21992/agones-s21992-server:v1
          imagePullPolicy: Always